### PR TITLE
Adding a chili recipe

### PR DESCRIPTION
**Pull request by mostlybob**
When I can swing it, this is one of my favourite chili recipes to do.

### CODE REVIEW

**Comment by rikai** [comment]
Can you reformat this according to [the recipe template in readme.md](https://github.com/rikai/OpenYourMouth/blob/master/README.md)? Thanks!

Also, after you've done that, if you wouldn't mind, could you squash your commits to a single commit and resubmit? Can learn about that [here](https://gun.io/blog/how-to-github-fork-branch-and-pull-request/)

Good chance to learn about ways to keep the commit log tidy! :)

Will happily merge it after, need more chili fo' sho'!

**Comment by mostlybob** [comment]
Hi rikai. I did the steps you suggested. Let me know of anything else that needs doing.

**Comment by mostlybob** [comment]
oops, dangit, I forgot to reformat the actual recipe. Nevermind the last comment. I'll take care of it and let you know.

**Comment by rikai** [comment]
Be sure to submit it as a new PR! :+1:

**Pull request closed without merging**
